package Login;

import java.awt.BorderLayout;
import java.awt.Component;
import java.util.Arrays;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import PanelsInGUI.GUI;


/**
*
* @author akash
*/
public class LoginGUI extends javax.swing.JPanel {
   private Component controllingFrame;

   /**
    * Creates new form ProjectGUI
    */
   public LoginGUI() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       welcomePanel = new javax.swing.JPanel();
       welcomeLabel = new javax.swing.JLabel();
       jLabel4 = new javax.swing.JLabel();
       jLabel6 = new javax.swing.JLabel();
       jLabel1 = new javax.swing.JLabel();
       loginPanel = new javax.swing.JPanel();
       userNameTextField1 = new javax.swing.JTextField();
       logInPasswordField = new javax.swing.JPasswordField();
       userNameLabel1 = new javax.swing.JLabel();
       passwordLabel1 = new javax.swing.JLabel();
       logInButton = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setBackground(new java.awt.Color(153, 255, 153));

       welcomePanel.setBackground(new java.awt.Color(255, 153, 0));

       welcomeLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
       welcomeLabel.setText("the Frugal Innovation Lab");

       jLabel4.setText("Please contact a super administrator if you are a new user or");

       jLabel6.setText("if you forgot your username or password.");

       jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
       jLabel1.setText("Welcome to");

       loginPanel.setBackground(new java.awt.Color(255, 255, 0));
       loginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

       userNameTextField1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               userNameTextField1ActionPerformed(evt);
           }
       });

       logInPasswordField.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               logInPasswordFieldActionPerformed(evt);
           }
       });

       userNameLabel1.setText("Username:");

       passwordLabel1.setText("Password:");

       logInButton.setText("Log In");
       logInButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               logInButtonActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
       loginPanel.setLayout(loginPanelLayout);
       loginPanelLayout.setHorizontalGroup(
           loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(loginPanelLayout.createSequentialGroup()
               .addContainerGap(50, Short.MAX_VALUE)
               .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(userNameLabel1)
                   .addComponent(passwordLabel1))
               .addGap(43, 43, 43)
               .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(logInButton)
                   .addComponent(logInPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                   .addComponent(userNameTextField1))
               .addContainerGap())
       );
       loginPanelLayout.setVerticalGroup(
           loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(loginPanelLayout.createSequentialGroup()
               .addGap(12, 12, 12)
               .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(userNameLabel1)
                   .addComponent(userNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(logInPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(passwordLabel1))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(logInButton)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
       welcomePanel.setLayout(welcomePanelLayout);
       welcomePanelLayout.setHorizontalGroup(
           welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(welcomePanelLayout.createSequentialGroup()
               .addGap(89, 89, 89)
               .addComponent(jLabel1)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(welcomePanelLayout.createSequentialGroup()
               .addGap(0, 150, Short.MAX_VALUE)
               .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(welcomePanelLayout.createSequentialGroup()
                       .addGap(81, 81, 81)
                       .addComponent(welcomeLabel))
                   .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(150, Short.MAX_VALUE))
       );
       welcomePanelLayout.setVerticalGroup(
           welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(welcomePanelLayout.createSequentialGroup()
               .addContainerGap(36, Short.MAX_VALUE)
               .addComponent(jLabel1)
               .addGap(2, 2, 2)
               .addComponent(welcomeLabel)
               .addGap(24, 24, 24)
               .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(35, 35, 35)
               .addComponent(jLabel4)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jLabel6)
               .addGap(36, 36, 36))
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>                        

   private void userNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
       // TODO add your handling code here:
   }                                                  

   private void logInPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
       // TODO add your handling code here:
   }                                                  

   private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
       char[] input = logInPasswordField.getPassword();
       System.out.println(new String(input));
       boolean value = isPasswordCorrect(input);
       System.out.println(value);
       if (isPasswordCorrect(input)) {
           JOptionPane.showMessageDialog(controllingFrame,
               "Success! You typed the right password.");
           //GUI gui = new GUI();
           //gui.cardLayout.show(gui.getMainPanel(), "User Registration");
       } else {
           JOptionPane.showMessageDialog(controllingFrame,
               "Invalid password. Try again.",
               "Error Message",
               JOptionPane.ERROR_MESSAGE);
       }
   }                                           

   private static boolean isPasswordCorrect(char[] input) {
   boolean isCorrect = true;
   char[] correctPassword = { 'b', 'u', 'g', 'a', 'b', 'o', 'o' };

   if (input.length != correctPassword.length) {
       isCorrect = false;
   } else {
       isCorrect = Arrays.equals (input, correctPassword);
   }

   //Zero out the password.
   //Arrays.fill(correctPassword,'0');

   return isCorrect;
   }
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new LoginGUI().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JButton logInButton;
   private javax.swing.JPasswordField logInPasswordField;
   private javax.swing.JPanel loginPanel;
   private javax.swing.JLabel passwordLabel1;
   private javax.swing.JLabel userNameLabel1;
   private javax.swing.JTextField userNameTextField1;
   private javax.swing.JLabel welcomeLabel;
   private javax.swing.JPanel welcomePanel;
   // End of variables declaration                   
}



