package PanelsInGUI;

import java.awt.*;
import javax.swing.*;
import AssignUsersToProjects.*;


/**
 *
 * @author akash
 */
public class AssignUsersToProjectsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignUsersToProjectsPanel
     */
	JTable jtable1;
	AssignUsersToProjectsController assignUsersToProjectsController = new AssignUsersToProjectsController(this);
    public AssignUsersToProjectsPanel() {
        initComponents();
        assignUsersToProjectsController = new AssignUsersToProjectsController(this);
        addButtonJTable();
    }
    
    public void addButtonJTable() {
		// addButton the data and column names to a JTable
		//jtable1  = new JTable(UserListTableController.getData(), UserListTableController.getColumnNames());
	   
	    jtable1 = new JTable(assignUsersToProjectsController.getTableModel());
		// addButton a ListSelectionListener to the table
		jtable1.getSelectionModel().addListSelectionListener(assignUsersToProjectsController);
		
		// addButton the table to a scrollpane
		JScrollPane scrollpane = new JScrollPane(jtable1);
		userSearchResultPanel.setLayout(new BorderLayout());
		userSearchResultPanel.add(scrollpane, BorderLayout.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        AssignUsersToProjectsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        projectNameTextField = new javax.swing.JTextField();
        addProjectsToUserPanel = new javax.swing.JPanel();
        userSearchResultPanel = new javax.swing.JPanel();
        projectsByUserPanel = new javax.swing.JPanel();
        selectUserButton = new javax.swing.JButton();
        updateUserButton = new javax.swing.JButton();
        addUsersToAProjectPanel = new javax.swing.JPanel();
        projectSearchResultPanel = new javax.swing.JPanel();
        usersInAProjectPanel = new javax.swing.JPanel();
        updateProjectButton = new javax.swing.JButton();
        selectProjectButton = new javax.swing.JButton();
        searchUserButton = new javax.swing.JButton();
        searchProjectButton = new javax.swing.JButton();

        AssignUsersToProjectsPanel.setBackground(new java.awt.Color(255, 255, 102));
        AssignUsersToProjectsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Assign Users to Projects"));

        jLabel1.setText("User Name:");

        jLabel2.setText("Project Name:");

        userNameTextField.setText("jTextField1");
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });

        projectNameTextField.setText("jTextField2");
        projectNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectNameTextFieldActionPerformed(evt);
            }
        });

        addProjectsToUserPanel.setBackground(new java.awt.Color(255, 153, 51));
        addProjectsToUserPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Projects to User"));

        userSearchResultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("User Search Result"));

        javax.swing.GroupLayout userSearchResultPanelLayout = new javax.swing.GroupLayout(userSearchResultPanel);
        userSearchResultPanel.setLayout(userSearchResultPanelLayout);
        userSearchResultPanelLayout.setHorizontalGroup(
            userSearchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        userSearchResultPanelLayout.setVerticalGroup(
            userSearchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        projectsByUserPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Projects by User"));

        javax.swing.GroupLayout projectsByUserPanelLayout = new javax.swing.GroupLayout(projectsByUserPanel);
        projectsByUserPanel.setLayout(projectsByUserPanelLayout);
        projectsByUserPanelLayout.setHorizontalGroup(
            projectsByUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        projectsByUserPanelLayout.setVerticalGroup(
            projectsByUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        selectUserButton.setText("Select User");
        selectUserButton.setActionCommand("");

        updateUserButton.setText("Update");

        javax.swing.GroupLayout addProjectsToUserPanelLayout = new javax.swing.GroupLayout(addProjectsToUserPanel);
        addProjectsToUserPanel.setLayout(addProjectsToUserPanelLayout);
        addProjectsToUserPanelLayout.setHorizontalGroup(
            addProjectsToUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProjectsToUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addProjectsToUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userSearchResultPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProjectsToUserPanelLayout.createSequentialGroup()
                        .addComponent(projectsByUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(addProjectsToUserPanelLayout.createSequentialGroup()
                .addGroup(addProjectsToUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addProjectsToUserPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(selectUserButton))
                    .addGroup(addProjectsToUserPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(updateUserButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addProjectsToUserPanelLayout.setVerticalGroup(
            addProjectsToUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProjectsToUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userSearchResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectsByUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(updateUserButton))
        );

        addUsersToAProjectPanel.setBackground(new java.awt.Color(255, 153, 51));
        addUsersToAProjectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Users to a Project"));

        projectSearchResultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Project Search Result"));

        javax.swing.GroupLayout projectSearchResultPanelLayout = new javax.swing.GroupLayout(projectSearchResultPanel);
        projectSearchResultPanel.setLayout(projectSearchResultPanelLayout);
        projectSearchResultPanelLayout.setHorizontalGroup(
            projectSearchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        projectSearchResultPanelLayout.setVerticalGroup(
            projectSearchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );

        usersInAProjectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Users in a Project"));

        javax.swing.GroupLayout usersInAProjectPanelLayout = new javax.swing.GroupLayout(usersInAProjectPanel);
        usersInAProjectPanel.setLayout(usersInAProjectPanelLayout);
        usersInAProjectPanelLayout.setHorizontalGroup(
            usersInAProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        usersInAProjectPanelLayout.setVerticalGroup(
            usersInAProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        updateProjectButton.setText("Update");

        selectProjectButton.setText("Select Project");
        selectProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addUsersToAProjectPanelLayout = new javax.swing.GroupLayout(addUsersToAProjectPanel);
        addUsersToAProjectPanel.setLayout(addUsersToAProjectPanelLayout);
        addUsersToAProjectPanelLayout.setHorizontalGroup(
            addUsersToAProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectSearchResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addUsersToAProjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addUsersToAProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUsersToAProjectPanelLayout.createSequentialGroup()
                        .addComponent(usersInAProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUsersToAProjectPanelLayout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addComponent(selectProjectButton)
                        .addGap(81, 81, 81))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUsersToAProjectPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateProjectButton)
                .addGap(100, 100, 100))
        );
        addUsersToAProjectPanelLayout.setVerticalGroup(
            addUsersToAProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUsersToAProjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectSearchResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectProjectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usersInAProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProjectButton))
        );

        searchUserButton.setText("Search User");
        
        searchUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserButtonActionPerformed(evt);
            }
        });
        searchProjectButton.setText("Search Project");

        javax.swing.GroupLayout AssignUsersToProjectsPanelLayout = new javax.swing.GroupLayout(AssignUsersToProjectsPanel);
        AssignUsersToProjectsPanel.setLayout(AssignUsersToProjectsPanelLayout);
        AssignUsersToProjectsPanelLayout.setHorizontalGroup(
            AssignUsersToProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssignUsersToProjectsPanelLayout.createSequentialGroup()
                .addGroup(AssignUsersToProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AssignUsersToProjectsPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AssignUsersToProjectsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addProjectsToUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 27, Short.MAX_VALUE)
                .addGroup(AssignUsersToProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AssignUsersToProjectsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addUsersToAProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(AssignUsersToProjectsPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(searchUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchProjectButton)
                .addGap(102, 102, 102))
        );
        AssignUsersToProjectsPanelLayout.setVerticalGroup(
            AssignUsersToProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssignUsersToProjectsPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(AssignUsersToProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AssignUsersToProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchUserButton)
                    .addComponent(searchProjectButton))
                .addGap(4, 4, 4)
                .addGroup(AssignUsersToProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUsersToAProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addProjectsToUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AssignUsersToProjectsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AssignUsersToProjectsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void projectNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void selectProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   
    public void updateTable() {
    	jtable1.setModel(assignUsersToProjectsController.getTableModel());
    }
    
    private void searchUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	//addButton a row to the table
    	String user_id = userNameTextField.getText(); 
    	
    	Component controllingFrame = null;
    	if(user_id == null){
    		int count = 0;
        	JOptionPane.showMessageDialog( controllingFrame,"You need to enter a unique user ID number.", "Error Message", JOptionPane.ERROR_MESSAGE);
    	}
    	else{
    		assignUsersToProjectsController.readUserByUserID(user_id);
    	}
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JPanel AssignUsersToProjectsPanel;
    private javax.swing.JPanel addProjectsToUserPanel;
    private javax.swing.JPanel addUsersToAProjectPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JPanel projectSearchResultPanel;
    private javax.swing.JPanel projectsByUserPanel;
    private javax.swing.JButton searchProjectButton;
    private javax.swing.JButton searchUserButton;
    private javax.swing.JButton selectProjectButton;
    private javax.swing.JButton selectUserButton;
    private javax.swing.JButton updateProjectButton;
    private javax.swing.JButton updateUserButton;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JPanel userSearchResultPanel;
    private javax.swing.JPanel usersInAProjectPanel;
    // End of variables declaration                   
}
