package PanelsInGUI;

import java.awt.BorderLayout;

import javax.swing.JScrollPane;
import javax.swing.JTable;

import UserRegistration.UserRegistrationController;
import DisplayProject.DisplayProjectController;

/**
 *
 * @author akash
 */
public class DisplayProjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayProjectPanel
     */
	private JTable jtable1;
    private DisplayProjectController DisplayProjectController; // glue between model and gui

	
    public DisplayProjectPanel() {
    	
        initComponents();
        DisplayProjectController = new DisplayProject.DisplayProjectController(this);
        addButtonJTable();
		//System.out.println(GUI.projectname);
        //projectNameTextField.setText(GUI.projectname);
        
        
    }
    
    public void addButtonJTable() {
		// addButton the data and column names to a JTable
		//jtable1  = new JTable(UserListTableController.getData(), UserListTableController.getColumnNames());
	   
	    jtable1 = new JTable(DisplayProjectController.getTableModel());
		// addButton a ListSelectionListener to the table
		jtable1.getSelectionModel().addListSelectionListener(DisplayProjectController);
		
		// addButton the table to a scrollpane
		JScrollPane scrollpane = new JScrollPane(jtable1);
		downloadFilesPanel.setLayout(new BorderLayout());
		downloadFilesPanel.add(scrollpane, BorderLayout.CENTER);
    }
    
    public void updateTable() {
    	jtable1.setModel(DisplayProjectController.getTableModel());
    }
    
    public void setProjectNameTextField(String val) {
		projectNameTextField.setText(val);
	}
    
    public void setCategoryTextField(String val) {
		categoryTextField.setText(val);
	}
    
    public void setStatusTextField(String val) {
		statusTextField.setText(val);
	}
    
    public void setDescriptionTextArea(String val) {
		descriptionTextArea.setText(val);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        displayProjectPanel = new javax.swing.JPanel();
        projectNameLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        categoryTextField = new javax.swing.JTextField();
        statusTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        downloadFilesPanel = new javax.swing.JPanel();

        displayProjectPanel.setBackground(new java.awt.Color(255, 255, 102));
        displayProjectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display Project", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 0, 0))); // NOI18N

        projectNameLabel.setText("Project Name:");

        categoryLabel.setText("Category:");

        statusLabel.setText("Status:");

        descriptionLabel.setText("Description:");

        //Changed here.
        String nameT = GUI.projectname; 
        System.out.println("++++++++++++++++++++"+nameT);
        projectNameTextField.setText(nameT);

        categoryTextField.setText(GUI.projectcat);
        categoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTextFieldActionPerformed(evt);
            }
        });

        statusTextField.setText(GUI.projectstatus);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        downloadFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Files in the Project"));

        javax.swing.GroupLayout downloadFilesPanelLayout = new javax.swing.GroupLayout(downloadFilesPanel);
        downloadFilesPanel.setLayout(downloadFilesPanelLayout);
        downloadFilesPanelLayout.setHorizontalGroup(
            downloadFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        downloadFilesPanelLayout.setVerticalGroup(
            downloadFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout displayProjectPanelLayout = new javax.swing.GroupLayout(displayProjectPanel);
        displayProjectPanel.setLayout(displayProjectPanelLayout);
        displayProjectPanelLayout.setHorizontalGroup(
            displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayProjectPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(downloadFilesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(displayProjectPanelLayout.createSequentialGroup()
                        .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(displayProjectPanelLayout.createSequentialGroup()
                                .addComponent(projectNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(projectNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addGroup(displayProjectPanelLayout.createSequentialGroup()
                                .addComponent(categoryLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(displayProjectPanelLayout.createSequentialGroup()
                                .addComponent(statusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(displayProjectPanelLayout.createSequentialGroup()
                                .addComponent(descriptionLabel)
                                .addGap(167, 167, 167))
                            .addComponent(jScrollPane1))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        displayProjectPanelLayout.setVerticalGroup(
            displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayProjectPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayProjectPanelLayout.createSequentialGroup()
                        .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(projectNameLabel)
                            .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(displayProjectPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(categoryLabel))
                            .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusLabel)
                            .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(displayProjectPanelLayout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(downloadFilesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void categoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 


    // Variables declaration - do not modify                     
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JPanel displayProjectPanel;
    private javax.swing.JPanel downloadFilesPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTextField;
    // End of variables declaration                   
}

