package PanelsInGUI;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Arrays;

import javax.persistence.Persistence;
import javax.swing.JOptionPane;

import Login.LoginController;
import Login.LoginTableModel;
import PanelsInGUI.GUI;
import UserRegistration.UserRegistration;
import UserRegistration.UserRegistrationService;


/**
 *
 * @author akash
 */
public class LoginPanel extends javax.swing.JPanel {

	private static final String PERSISTENCE_UNIT_NAME = "PersistenceUnit";  // Used in persistence.xml
    private Component controllingFrame;
    private LoginController loginController;

	/**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
    	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
    	 welcomePanel = new javax.swing.JPanel();
         welcomeLabel = new javax.swing.JLabel();
         jLabel4 = new javax.swing.JLabel();
         jLabel6 = new javax.swing.JLabel();
         jLabel1 = new javax.swing.JLabel();
         loginPanel = new javax.swing.JPanel();
         userNameTextField1 = new javax.swing.JTextField();
         logInPasswordField = new javax.swing.JPasswordField();
         userNameLabel1 = new javax.swing.JLabel();
         passwordLabel1 = new javax.swing.JLabel();
         logInButton = new javax.swing.JButton();

         welcomePanel.setBackground(new java.awt.Color(255, 153, 0));

         welcomeLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
         welcomeLabel.setText("the Frugal Innovation Lab");

         jLabel4.setText("Please contact a super administrator if you are a new user or");

         jLabel6.setText("if you forgot your username or password.");

         jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
         jLabel1.setText("Welcome to");

         loginPanel.setBackground(new java.awt.Color(255, 255, 0));
         loginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

         userNameTextField1.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 userNameTextField1ActionPerformed(evt);
             }
         });

         logInPasswordField.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 logInPasswordFieldActionPerformed(evt);
             }
         });

         userNameLabel1.setText("Username:");

         passwordLabel1.setText("Password:");

         logInButton.setText("Log In");
         logInButton.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 logInButtonActionPerformed(evt);
             }
         });

         javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
         loginPanel.setLayout(loginPanelLayout);
         loginPanelLayout.setHorizontalGroup(
             loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(loginPanelLayout.createSequentialGroup()
                 .addContainerGap(50, Short.MAX_VALUE)
                 .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(userNameLabel1)
                     .addComponent(passwordLabel1))
                 .addGap(43, 43, 43)
                 .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(logInButton)
                     .addComponent(logInPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                     .addComponent(userNameTextField1))
                 .addContainerGap())
         );
         loginPanelLayout.setVerticalGroup(
             loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(loginPanelLayout.createSequentialGroup()
                 .addGap(12, 12, 12)
                 .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(userNameLabel1)
                     .addComponent(userNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(logInPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(passwordLabel1))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addComponent(logInButton)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );

         javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
         welcomePanel.setLayout(welcomePanelLayout);
         welcomePanelLayout.setHorizontalGroup(
             welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(welcomePanelLayout.createSequentialGroup()
                 .addGap(89, 89, 89)
                 .addComponent(jLabel1)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addGroup(welcomePanelLayout.createSequentialGroup()
                 .addGap(0, 150, Short.MAX_VALUE)
                 .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(welcomePanelLayout.createSequentialGroup()
                         .addGap(81, 81, 81)
                         .addComponent(welcomeLabel))
                     .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addContainerGap(150, Short.MAX_VALUE))
         );
         welcomePanelLayout.setVerticalGroup(
             welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(welcomePanelLayout.createSequentialGroup()
                 .addContainerGap(36, Short.MAX_VALUE)
                 .addComponent(jLabel1)
                 .addGap(2, 2, 2)
                 .addComponent(welcomeLabel)
                 .addGap(24, 24, 24)
                 .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGap(35, 35, 35)
                 .addComponent(jLabel4)
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addComponent(jLabel6)
                 .addGap(36, 36, 36))
         );

         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
         this.setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
    }// </editor-fold>                        

    private void userNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:

    }                                                  

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	int userID =Integer.parseInt(userNameTextField1.getText());
        System.out.println(""+userID);
        String password = new String(logInPasswordField.getPassword());
        System.out.println(""+password);
        LoginTableModel auth = new LoginTableModel();
        boolean isCorrect = auth.authorization(userID, password);
		if (isCorrect) {
            JOptionPane.showMessageDialog(controllingFrame,
                "Success! You typed the right password.");

        	GUI.getMainPanel().add(new OptionPanel(), "Select Panel");
            CardLayout cl = (CardLayout)(PanelsInGUI.GUI.getMainPanel().getLayout());
            cl.show(PanelsInGUI.GUI.getMainPanel(), "Select Panel");
        } else {
            JOptionPane.showMessageDialog(controllingFrame,
                "Invalid password. Try again.",
                "Error Message",
                JOptionPane.ERROR_MESSAGE);
        }
    }                                           

    private void logInPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:

    }      
   


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton logInButton;
    private javax.swing.JPasswordField logInPasswordField;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JLabel userNameLabel1;
    private javax.swing.JTextField userNameTextField1;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel welcomePanel;
    
    // End of variables declaration                   
}
