package PanelsInGUI;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Arrays;

import javax.persistence.Persistence;
import javax.swing.JOptionPane;

import Login.LoginController;
import Login.LoginTableModel;
import PanelsInGUI.GUI;
import UserRegistration.UserRegistration;
import UserRegistration.UserRegistrationService;


/**
 *
 * @author akash
 */
public class LoginPanel extends javax.swing.JPanel {

	private static final String PERSISTENCE_UNIT_NAME = "PersistenceUnit";  // Used in persistence.xml
    private Component controllingFrame;
    private LoginController loginController;

	/**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
    	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
        loginPanel1 = new javax.swing.JPanel();
        userNameLabel1 = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        userNameTextField1 = new javax.swing.JTextField();
        logInButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        logInPasswordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        loginPanel1.setBackground(new java.awt.Color(255, 153, 0));

        userNameLabel1.setText("UserID:");

        passwordLabel1.setText("Password:");

        userNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextField1ActionPerformed(evt);
            }
        });

        logInButton.setText("Log In");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        welcomeLabel.setText("Welcome to the Frugal Innovation Lab");

        logInPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInPasswordFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Please contact a super administrator if you are a new user or");

        jLabel6.setText("if you forgot your username or password.");

        javax.swing.GroupLayout loginPanel1Layout = new javax.swing.GroupLayout(loginPanel1);
        loginPanel1.setLayout(loginPanel1Layout);
        loginPanel1Layout.setHorizontalGroup(
            loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel1Layout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addGroup(loginPanel1Layout.createSequentialGroup()
                        .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLabel1)
                            .addComponent(userNameLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logInButton)
                            .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userNameTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(logInPasswordField))))
                    .addGroup(loginPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        loginPanel1Layout.setVerticalGroup(
            loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logInPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logInButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loginPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(loginPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
    }// </editor-fold>                        

    private void userNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:

    }                                                  

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	int userID =Integer.parseInt(userNameTextField1.getText());
        System.out.println(""+userID);
        String password = new String(logInPasswordField.getPassword());
        System.out.println(""+password);
        LoginTableModel auth = new LoginTableModel();
        boolean isCorrect = auth.authorization(userID, password);
		if (isCorrect) {
            JOptionPane.showMessageDialog(controllingFrame,
                "Success! You typed the right password.");
            //GUI gui = new GUI();
            //gui.cardLayout.show(gui.mainPanel,"User Registration Panel");
            CardLayout cl = (CardLayout)(PanelsInGUI.GUI.getMainPanel().getLayout());
            cl.show(PanelsInGUI.GUI.getMainPanel(), "User Registration Panel");
        } else {
            JOptionPane.showMessageDialog(controllingFrame,
                "Invalid password. Try again.",
                "Error Message",
                JOptionPane.ERROR_MESSAGE);
        }
    }                                           

    private void logInPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:

    }      
   


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton logInButton;
    private javax.swing.JPasswordField logInPasswordField;
    private javax.swing.JPanel loginPanel1;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JLabel userNameLabel1;
    private javax.swing.JTextField userNameTextField1;
    private javax.swing.JLabel welcomeLabel;
    //public static int userID;
    //public static String password;
    
    // End of variables declaration                   
}
