package PanelsInGUI;

import java.awt.CardLayout;
/**
*
* @author akash
*/
public class OptionPanel extends javax.swing.JPanel {

   /**
    * Creates new form OptionPanel
    */
   public OptionPanel() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       chooseAnOptionPanel = new javax.swing.JPanel();
       userManagement = new javax.swing.JButton();
       projectManagement = new javax.swing.JButton();
       displayProjects = new javax.swing.JButton();
       jButton1 = new javax.swing.JButton();
       jButton2 = new javax.swing.JButton();
       jButton3 = new javax.swing.JButton();
       jButton4 = new javax.swing.JButton();
       jLabel1 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       jLabel4 = new javax.swing.JLabel();

       chooseAnOptionPanel.setBackground(new java.awt.Color(255, 255, 51));
       chooseAnOptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose an Option"));

       userManagement.setText("User Management");
       userManagement.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               userManagementActionPerformed(evt);
           }
       });

       projectManagement.setText("Project Management");
       projectManagement.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               projectManagementActionPerformed(evt);
           }
       });

       displayProjects.setText("Display Projects");
       displayProjects.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               displayProjectsActionPerformed(evt);
           }
       });

       jButton1.setIcon(new javax.swing.ImageIcon("/Users/akash/Desktop/frugallabpics/frugalLabpic1.png")); // NOI18N
       jButton1.setAlignmentY(0.0F);
       jButton1.setIconTextGap(0);

       jButton2.setIcon(new javax.swing.ImageIcon("/Users/akash/Desktop/frugallabpics/frugalLabpic5.png")); // NOI18N

       jButton3.setIcon(new javax.swing.ImageIcon("/Users/akash/Desktop/frugallabpics/frugalLabpic3.png")); // NOI18N
       jButton3.setText("jButton3");

       jButton4.setIcon(new javax.swing.ImageIcon("/Users/akash/Desktop/frugallabpics/frugalLabPic4.png")); // NOI18N
       jButton4.setText("jButton4");

       jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
       jLabel1.setText("Innovation & Technology");

       jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
       jLabel2.setText("Immersion");

       jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
       jLabel3.setText("Community Service");

       jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
       jLabel4.setText("Teach Students");

       javax.swing.GroupLayout chooseAnOptionPanelLayout = new javax.swing.GroupLayout(chooseAnOptionPanel);
       chooseAnOptionPanel.setLayout(chooseAnOptionPanelLayout);
       chooseAnOptionPanelLayout.setHorizontalGroup(
           chooseAnOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(chooseAnOptionPanelLayout.createSequentialGroup()
               .addGap(18, 18, 18)
               .addGroup(chooseAnOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
               .addGroup(chooseAnOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(chooseAnOptionPanelLayout.createSequentialGroup()
                       .addGap(25, 25, 25)
                       .addComponent(displayProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(chooseAnOptionPanelLayout.createSequentialGroup()
                       .addGap(18, 18, 18)
                       .addGroup(chooseAnOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(projectManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(userManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
               .addGap(18, 18, 18)
               .addGroup(chooseAnOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(19, Short.MAX_VALUE))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseAnOptionPanelLayout.createSequentialGroup()
               .addGap(71, 71, 71)
               .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(145, 145, 145))
           .addGroup(chooseAnOptionPanelLayout.createSequentialGroup()
               .addGap(86, 86, 86)
               .addComponent(jLabel3)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(59, 59, 59))
       );
       chooseAnOptionPanelLayout.setVerticalGroup(
           chooseAnOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(chooseAnOptionPanelLayout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(chooseAnOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel2)
                   .addComponent(jLabel4))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(chooseAnOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                   .addGroup(chooseAnOptionPanelLayout.createSequentialGroup()
                       .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(chooseAnOptionPanelLayout.createSequentialGroup()
                       .addComponent(userManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(134, 134, 134)
                       .addComponent(projectManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(136, 136, 136)
                       .addComponent(displayProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(chooseAnOptionPanelLayout.createSequentialGroup()
                       .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(28, 28, 28)
                       .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGap(18, 18, 18)
               .addGroup(chooseAnOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel3)
                   .addComponent(jLabel1))
               .addContainerGap())
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(chooseAnOptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(chooseAnOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addContainerGap())
       );
   }// </editor-fold>                        

   private void userManagementActionPerformed(java.awt.event.ActionEvent evt) {                                               
       // TODO add your handling code here:
		GUI.getMainPanel().add(new UserRegistrationPanel(), "User Registration Panel");
		CardLayout cl = (CardLayout)(PanelsInGUI.GUI.getMainPanel().getLayout());
	    cl.show(PanelsInGUI.GUI.getMainPanel(), "User Registration Panel");
   }                                              

   private void projectManagementActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       // TODO add your handling code here:
		GUI.getMainPanel().add(new ProjectManagementPanel(), "Project Management Panel");
		CardLayout cl = (CardLayout)(PanelsInGUI.GUI.getMainPanel().getLayout());
	    cl.show(PanelsInGUI.GUI.getMainPanel(), "Project Management Panel");
   }                                                 

   private void displayProjectsActionPerformed(java.awt.event.ActionEvent evt) {                                                
       // TODO add your handling code here:
   }                                               


   // Variables declaration - do not modify                     
   private javax.swing.JPanel chooseAnOptionPanel;
   private javax.swing.JButton displayProjects;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JButton projectManagement;
   private javax.swing.JButton userManagement;
   // End of variables declaration                   
}

