package DisplayProject;

import java.awt.BorderLayout;
import java.awt.Component;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;


/**
*
* @author akash
*/
public class DisplayProjectGUI extends javax.swing.JFrame {

   /**
    * Creates new form DisplayProjectGUI
    */
   public DisplayProjectGUI() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       displayProjectPanel = new javax.swing.JPanel();
       projectNameLabel = new javax.swing.JLabel();
       categoryLabel = new javax.swing.JLabel();
       statusLabel = new javax.swing.JLabel();
       descriptionLabel = new javax.swing.JLabel();
       projectNameTextField = new javax.swing.JTextField();
       categoryTextField = new javax.swing.JTextField();
       statusTextField = new javax.swing.JTextField();
       jScrollPane1 = new javax.swing.JScrollPane();
       descriptionTextArea = new javax.swing.JTextArea();
       downloadFilesPanel = new javax.swing.JPanel();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       displayProjectPanel.setBackground(new java.awt.Color(255, 255, 102));
       displayProjectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display Project", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 0, 0))); // NOI18N

       projectNameLabel.setText("Project Name:");

       categoryLabel.setText("Category:");

       statusLabel.setText("Status:");

       descriptionLabel.setText("Description:");

       projectNameTextField.setText("jTextField1");

       categoryTextField.setText("jTextField2");
       categoryTextField.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               categoryTextFieldActionPerformed(evt);
           }
       });

       statusTextField.setText("jTextField3");

       descriptionTextArea.setColumns(20);
       descriptionTextArea.setRows(5);
       jScrollPane1.setViewportView(descriptionTextArea);

       downloadFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Files in the Project"));

       javax.swing.GroupLayout downloadFilesPanelLayout = new javax.swing.GroupLayout(downloadFilesPanel);
       downloadFilesPanel.setLayout(downloadFilesPanelLayout);
       downloadFilesPanelLayout.setHorizontalGroup(
           downloadFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 461, Short.MAX_VALUE)
       );
       downloadFilesPanelLayout.setVerticalGroup(
           downloadFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 112, Short.MAX_VALUE)
       );

       javax.swing.GroupLayout displayProjectPanelLayout = new javax.swing.GroupLayout(displayProjectPanel);
       displayProjectPanel.setLayout(displayProjectPanelLayout);
       displayProjectPanelLayout.setHorizontalGroup(
           displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(displayProjectPanelLayout.createSequentialGroup()
               .addGap(40, 40, 40)
               .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(downloadFilesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addGroup(displayProjectPanelLayout.createSequentialGroup()
                       .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addGroup(displayProjectPanelLayout.createSequentialGroup()
                               .addComponent(projectNameLabel)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                               .addComponent(projectNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                           .addGroup(displayProjectPanelLayout.createSequentialGroup()
                               .addComponent(categoryLabel)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                               .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(displayProjectPanelLayout.createSequentialGroup()
                               .addComponent(statusLabel)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                               .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                       .addGap(18, 18, 18)
                       .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addGroup(displayProjectPanelLayout.createSequentialGroup()
                               .addComponent(descriptionLabel)
                               .addGap(167, 167, 167))
                           .addComponent(jScrollPane1))))
               .addContainerGap(40, Short.MAX_VALUE))
       );
       displayProjectPanelLayout.setVerticalGroup(
           displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(displayProjectPanelLayout.createSequentialGroup()
               .addGap(8, 8, 8)
               .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(displayProjectPanelLayout.createSequentialGroup()
                       .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(projectNameLabel)
                           .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(displayProjectPanelLayout.createSequentialGroup()
                               .addGap(6, 6, 6)
                               .addComponent(categoryLabel))
                           .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addGroup(displayProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(statusLabel)
                           .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                   .addGroup(displayProjectPanelLayout.createSequentialGroup()
                       .addComponent(descriptionLabel)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
               .addComponent(downloadFilesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(36, 36, 36))
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(displayProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(displayProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>                        

   private void categoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       // TODO add your handling code here:
   }                                                 

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(DisplayProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(DisplayProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(DisplayProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(DisplayProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new DisplayProjectGUI().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JLabel categoryLabel;
   private javax.swing.JTextField categoryTextField;
   private javax.swing.JLabel descriptionLabel;
   private javax.swing.JTextArea descriptionTextArea;
   private javax.swing.JPanel displayProjectPanel;
   private javax.swing.JPanel downloadFilesPanel;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JLabel projectNameLabel;
   private javax.swing.JTextField projectNameTextField;
   private javax.swing.JLabel statusLabel;
   private javax.swing.JTextField statusTextField;
   // End of variables declaration                   
}



